name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-core
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: pnpm setup
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

  ci-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-web
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: pnpm setup
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build